classes:
- id: 1
  name: person
  color: '#ff1744'
  shortcut: '1'
  visible: true
  description: ''
- id: 2
  name: vehicle
  color: '#00e676'
  shortcut: '2'
  visible: true
  description: ''
- id: 3
  name: bicycle
  color: '#2979ff'
  shortcut: '3'
  visible: true
  description: ''
